#!/bin/bash
git clone https://$GITHUB_TOKEN@github.com/$AUTHOR/$REPONAME.git ../gcc-arm
rm -rf ../gcc-arm/*
bash gccwrap.sh -a arm
script_dir=$(pwd)
cd ../gcc-arm
./bin/arm-linux-gnueabi-gcc -v 2>&1 |& tee /tmp/gcc-arm-version
git add . -f
git commit -as -m "Build Arm GCC xea-xo1-gcc" -m "Build completed on: $(/bin/date)" -m "Configuration: $(/bin/cat /tmp/gcc-arm-version)"
git gc
git checkout -b arm
git push https://$GITHUB_TOKEN@github.com/$AUTHOR/$REPONAME.git -f
