#!bin/bash/env bash
git clone https://$GITHUB_TOKEN@github.com/$AUTHOR/$REPONAME.git ../gcc-arm64
rm -rf ../gcc-arm64/*
bash gccwrap.sh -a arm64
bash build-lld.sh -a arm64
script_dir=$(pwd)
cd ../gcc-arm64
bash "$script_dir/strip-binaries.sh"
./bin/aarch64-elf-gcc -v 2>&1 |& tee /tmp/gcc-arm64-version
git add . -f
git commit -as -m "Build Arm64 Gcc $NAMEPKG" -m "Build completed on: $(/bin/date)" -m "Configuration: $(/bin/cat /tmp/gcc-arm64-version)"
git gc
git checkout -b 64
git push https://$GITHUB_TOKEN@github.com/$AUTHOR/$REPONAME.git -f
