--- 
clone: 
  depth: 1
kind: pipeline
name: ARM
steps: 
  - 
    commands: 
      - apt-get -y install ninja-build build-essential make 
      - chmod +x gccwrap.sh
      - chmod +x .github/x86
      - chmod +x build-lld.sh
      - bash .github/x86
    environment: 
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
      AUTHOR:
        from_secret: MARKER
      REPONAME:
        from_secret: REPONAME
      NAMEPKG:
        from_secret: TOOCHAIN_NAME
      TOKEN:
        from_secret: TOKEN_BOT
      ID:
        from_secret: CHAT_ID
    image: xealea/xea:01
    name: builder
    trigger: 
      branch: 
        - unified-tes
